### ISSUE TITLE
bug: app saving config files in gigabytes

### ISSUE THREAD

**Issue by Karamveer9200** [vikdevelop/SaveDesktop#209]
### Linux distribution

Fedora 39

### Desktop Environment

GNOME

### Package type

Flatpak from Flathub

### Bug description

After the update. App increases the size of the compressed config(even without faltpak) exponentially (in few gigabytes).

**Comment by Karamveer9200** [comment]
It seems like application is not ignoring user config files for the faltpak .

**Comment by vikdevelop** [comment]
Hello, thank you for your bug request.
1) the bug with duplicating tarball archive I've fixed, so it will be in the next release version fixed.
2) the problem you describe with Flatpak saving data is not really a problem. The reason the "Flatpak apps" switch does not turn off the Flatpak app data storage switch is so that the user can choose to save only the list of installed Flatpak apps or also their data.

**Comment by Karamveer9200** [comment]
thanks for the clarification.

**Comment by Karamveer9200** [comment]
thanks for the clarification.
