### ISSUE TITLE
question: Does the extensions toggle also save the settings of the extensions?

### ISSUE THREAD

**Issue by back-lacking** [vikdevelop/SaveDesktop#267]
### Your question

Exactly what it sounds like, does the extensions toggle in the app include the settings of the extensions?

**Comment by vikdevelop** [comment]
Hello,
thank you for your question.
Since the extension user settings are stored in the Dconf database (this is the dconf-settings.ini file in your configuration archive), then yes, the extension user settings are also stored. The switch you mentioned is intended to ensure that when it is disabled, the folder with installed extensions is not saved (e.g. for GNOME it is `~/.local/share/gnome-shell/extensions`, this folder contains the source files of the extensions only, not the user data).
