### ISSUE TITLE
feature_request: Password protection

### ISSUE THREAD

**Issue by Vovkiv** [vikdevelop/SaveDesktop#270]
### The current problem or need

While data such as gnome settings might not have some sensetive information, flatpak apps data folder might have, like browser history and passwords or 2FA data (such as https://gitlab.gnome.org/World/Authenticator).
Since user might make backups on removable devices (such as usb flash drives), they might not encrypt them, as result saving entire flatpak data (if user included such data) in single, non encrypted archieve.
So if something happens (like user lost somewhere their usb flash driver), they will leave it exposed with everything to someone who will be lucky to found that lost usb flash drive. 

### Describe the solution you'd like

* There should be UI during archieve creation with option to enter password and maybe some explanation why user might want to make password-protected archieve.
* UI during archieve importing, where user will be promted to enter password.
* I'm not sure how peridiocal saving should work with this. Saving user-entered password in plain text doesn't sound that safe.
* I didn't used network features of SaveDesktop, but it also probbaly might require some work?

**Comment by vikdevelop** [comment]
Hello,
thank you for your feature request.
This change would mean a fairly significant "overhaul" of the user interface and source code. However, I don't rule out trying to implement this change in a future version of the application (maybe even 3.3).

**Comment by vikdevelop** [comment]
Hello, I added this feature to release 3.3 (on this repo, it is a rel33 branch). If you want to try it, you can use these commands:
```sh
git clone https://github.com/vikdevelop/SaveDesktop --branch=rel33
cd SaveDesktop
```
You can use Flatpak builder (`flatpak-builder build *.yaml --install --user`, you need org.gnome.Sdk v46 installed) or install it as a native package (`sh native/install_native.sh --install`, you need to at least have GTK 4.10 and LiAdwaita 1.3 installed)

Instead of the Tar Gzip format, SaveDesktop uses the ZIP format if archive encryption is enabled.

Encrypting periodic saving files as well as the synchronisation are so far disabled because I don't know the most user-friendly way to require a password from an encrypted archive.

In addition to these features, the following new features are available in this version:
<li>Added option to save configuration from command-line interface (more information is also available on the Github wiki)</li>
<li>Added support for Deepin DE</li>
<li>Added support for saving Kvantum Manager and Latte dock configurations</li>

I am planning to release this version in the following days. I would be interested in your opinion, whether it works for you, etc.
