### ISSUE TITLE
feature_request: Request for Setup.py or Makefile for SaveDesktop Packaging on FreeBSD

### ISSUE THREAD

**Issue by nxjosephofficial** [vikdevelop/SaveDesktop#311]
### The current problem or need

Hello, I hope this message finds you well! I am currently working on packaging SaveDesktop for the FreeBSD operating system and have encountered a small challenge. The ports framework requires either a `setup.py` file or a `Makefile` in the root directory for the packaging process. Would it be possible for you to provide either a `setup.py` file or a `Makefile`? Your assistance would be greatly appreciated and would help me move forward with this project. Thank you so much for your help! 

Best regards,
nxjoseph

### Describe the solution you'd like

I'd like to see either a `setup.py` file or a `Makefile`.

**Comment by vikdevelop** [comment]
Hello, 
thank you for your feature request.
I'm glad for your interest in porting SaveDesktop to FreeBSD! But, I apologize, I have no knowledge of how to write the `setup.py` file or `Makefile`, because I am distributing this app on the [Flathub](https://github.com/flathub/io.github.vikdevelop.SaveDesktop/blob/master/io.github.vikdevelop.SaveDesktop.yaml) or [Snap Store](https://github.com/vikdevelop/SaveDesktop/blob/main/snapcraft.yaml). But, if you have this knowledge, feel free to create a PR, as any contributions are welcome!

**Comment by nxjosephofficial** [comment]
Sorry, I've tried but I couldn't made it.
