### ISSUE TITLE
bug: icon missing on "Save" page

### ISSUE THREAD

**Issue by bannert1337** [vikdevelop/SaveDesktop#332]
### Linux distribution

CachyOS

### Desktop Environment

GNOME

### Version of the SaveDesktop app

3.4.1-native

### Package type

Native from this repository

### Bug description

![image](https://github.com/user-attachments/assets/671c68f4-6e6e-455e-ad6c-5245f659bcc6)

Installed through AUR.

**Comment by vikdevelop** [comment]
Hello, this means you have not installed the icon theme, which contains the missing icon. So, you can install the Tela icon theme to solve this trivial problem.

In Flatpak or Snap, I am solving this by adding some icons, which are available in the [`/flatpak/symbolic-icons/`](https://github.com/vikdevelop/SaveDesktop/tree/main/flatpak/symbolic-icons) directory of this repository.

If you want, you can also contact the real maintainer of the [AUR package](https://aur.archlinux.org/packages/savedesktop), because I am not maintaining this package.

**Comment by bannert1337** [comment]
Thank you for your reply, I will inform the AUR package maintainer!
