### ISSUE TITLE
[Feature] Add support for restoring flatpak and snap apps

### ISSUE THREAD

**Issue by hyuri** [vikdevelop/SaveDesktop#40]
Hi!

It would be awesome if the app could also restore our flatpak and snap apps as well.

I know you can generate an install list of your flatpak apps with something like:
`flatpak list --columns=origin --columns=application | awk '{print "flatpak install " $1,$2 " -y"}'`

And you can output that list to a bash file and execute, to get all your flatpaks installed.

Even better if the app could save and restore app data too, so that we can be up and running with all of our apps right away. I don't know about snaps but, for flatpaks, I think the data lives in `~.var/app`

Edit: I guess you would have to make sure flatpak and snap are installed.

**Comment by vikdevelop** [comment]
Hello,
SaveDesktop was not created as a system backup tool but as a tool to save desktop environment settings, icons, themes, backgrounds, etc... I'm not sure how flatpak or snap would run in the sandbox, except maybe with the org.freedesktop.Flatpak permission, which is already a permission that interferes quite a lot with the system. Anyway, I'll try to implement it.

**Comment by vikdevelop** [comment]
New version has been uploaded on Flathub. It availables to download will be in a few hours. But it can not save Flatpak apps data, because in the case of saving ~/.var/app directory it saves ~5 applications data, the rest nothing (SaveDesktop has access to this directory). So, at least I added option to save custom permissions of Flatpak apps.
